spring:
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  h2:
    console:
      enabled: true
  graphql:
    schema:
      # Default location is classpath:graphql/**/
      # BUT not working, so Use 'classpath*:' and then it works.

      # Issues
      # https://github.com/spring-projects/spring-boot/issues/31772

      # Related codes
      # https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/graphql/GraphQlProperties.java#L75
      locations: classpath*:graphql/**/
    graphiql:
      enabled: true
